name: ci-cd
on: [push]
jobs:
  ci-cd:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: examples/sqlalchemy
          cache-from: type=gha
          build-args: |
            COMMIT_SHA=${{ github.sha }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sed -i 's/^.*image:.*$/    image: ghcr.io\/yangbobo2021\/fastapi-users:${{ github.head_ref || github.ref_name }}/' /root/fastapi-users/compose.yml
            cd /root/fastapi-users && docker-compose up -d --pull always
